### ISSUE TITLE
source code of released version(s)

### ISSUE THREAD

**Issue by Mrxx99** [dotnetprojects/WpfToolkit#35]
Hi,
I wanted to use this NuGet package for a project at the company I work in. But the guidelines there require uploading the source code of the used version so that it can be approved. But I can't find what is the corresponding source code of the latest version. Seems like it is the last commit, but I need to know for sure. To avoid such issues you could simply use the release area on GitHub to release the source code for the version(s). 
![grafik](https://user-images.githubusercontent.com/33566379/39960868-caa3b508-562a-11e8-9010-30c4b7c3b563.png)

**Comment by jogibear9988** [comment]
I've no time to do this. Because we create a release automaticaly when a  pull request is merged to master.

You could change our nuget build to push the source to sourcelink https://github.com/dotnet/designs/blob/master/accepted/diagnostics/source-link.md#why-source-link

Atm. I've no time to do this myself

**Comment by ggeurts** [comment]
#37 adds SourceLink support

**Comment by jogibear9988** [comment]
fixed by sourcelink support
